---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "hass.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "hass.name" . }}
    chart: {{ template "hass.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
{{- range $name := .Values.dnsNames }}
  - host: {{ $name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hass
            port:
              name: http
{{- end }}
