image:
  repository: docker.io/homeassistant/home-assistant
  tag: 2020.12.0
  pullPolicy: IfNotPresent
  pullSecret:

# -- Number of replicas to run
replicaCount: 1

# -- Timezone
timezone: "Europe/Amsterdam"

service:
  type: ClusterIP
  port: 8123

# -- (list) List of DNS names the ingress should respond to
dnsNames:

# -- Path were the persistent data is stored on the host
mountPath: /data
