image:
  # -- Image to use
  repository: docker.io/homeassistant/home-assistant
  # -- Tag to use
  tag: 2020.12.1
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- (string) Optional image pull secret
  pullSecret:

# -- Number of replicas to run
replicaCount: 1

# -- Timezone
timezone: "Europe/Amsterdam"

service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 8123

# -- (list) List of DNS names the ingress should respond to
dnsNames:

# -- Path were the persistent data is stored on the host
mountPath: /data
