name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:

  lint-chart:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up chart-testing
        uses: helm/chart-testing-action@master
      - name: Run chart-testing (lint)
        env:
          CT_CHECK_VERSION_INCREMENT: false
          CT_DEBUG: true
          CT_TARGET_BRANCH: main
          CT_VALIDATE_MAINTAINERS: false
        run: ct lint

  lint-docs:
    runs-on: ubuntu-20.04
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-20.04
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.19.6
          - v1.20.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-20.04
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.19.4
          - v1.20.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@master
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up chart-testing
        uses: helm/chart-testing-action@master
      - name: Run chart-testing (install)
        env:
          CT_DEBUG: true
          CT_HELM_EXTRA_ARGS: "--timeout 600 --set dnsNames={hass.mydomain.com}"
          CT_TARGET_BRANCH: main
        run: ct install

